version: "3"

networks:
  petio-network:
    driver: bridge

services:
  petio:
    image: ghcr.io/petio-team/petio:latest
    container_name: petio
    hostname: petio
    ports:
      - "7777:7777"
    networks:
      - petio-network
    depends_on:
      - mongo
    user: "1000:1000"
    environment:
      - TZ=Etc/UTC
    volumes:
      - ./config:/app/api/config
      - ./logs:/app/logs

  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - petio-network
    user: "1000:1000"
    volumes:
      - ./db:/data/db
